### ISSUE TITLE
Access Manager Installation PHP Fatal Error

### ISSUE THREAD

**Issue by ceeci** [AccessManager/access-manager#8]
Hi,
Your app is awesome. I am interested and just as i followed installation guide i got this error after issuing the following command;
sudo composer create-project access-manager/access-manager 

Generating autoload files
PHP Fatal error:  Class 'Thujohn\Pdf\PdfServiceProvider' not found in /var/www/html/access-manager/laravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Thujohn\\Pdf\\PdfServiceProvider' not found","file":"\/var\/www\/html\/access-manager\/laravel\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}Script php laravel/artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Fatal error:  Class 'Thujohn\Pdf\PdfServiceProvider' not
  found in /var/www/html/access-manager/laravel/vendor/laravel/framework/src/
  Illuminate/Foundation/ProviderRepository.php on line 157
kindly find attaced snapshot
Thank you!!
![snapshot2](https://cloud.githubusercontent.com/assets/10342905/5572671/83c699e4-8f99-11e4-86e6-ddbc0f16392e.jpg)

**Comment by rahulmkhj** [comment]
Sorry, for the inconvenience, I missed that in last commit. Now its been rectified, please try once more.

**Comment by ceeci** [comment]
Thanks very much sir,
Sorry to border you again...I have crushed into another error just after issuing this command...
"php artisan migrate:refresh --seed"

"
Do you really wish to run this command? yes
PHP Fatal error:  Call to undefined method DirecpaySettings::insert() in /var/www/html/access-manager/laravel/app/database/seeds/DefaultsSeeder.php on line 60
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined method DirecpaySettings::insert()","file":"\/var\/www\/html\/access-manager\/laravel\/app\/database\/seeds\/DefaultsSeeder.php","line":60}}
ceeci@appserver:/var/www/html/access-manager/laravel$
"
Thanks Sir
![err_snapshot](https://cloud.githubusercontent.com/assets/10342905/5591917/24ef3c94-9194-11e4-985f-16051a943259.jpg)

**Comment by rahulmkhj** [comment]
I just tried it on my laptop & the process was smooth. If you face any issues with installation, kindly post them on http://forum.accessmanager.in

**Comment by ayprograms** [comment]
when i try to install access-manager i run into this problem

 [RuntimeException]                                                                                                     
  Error Output: PHP Fatal error:  Cannot redeclare makeExpiry() (previously declared in /var/www/html/access-manager/la  
  ravel/vendor/access-manager/am-helpers/src/Helpers.php:23) in /var/www/html/access-manager/laravel/app/helpers.php on  
   line 28
